name: `Pre-commit autoupdate`
description: `Runs pre-commit autoupdate, then runs against all files`
branding:
  icon: "chevrons-up"
  color: "purple"
runs:
  using: "composite"
  steps:
    - run: pip install pre-commit
      shell: bash
    - run: pre-commit autoupdate
      shell: bash
    - id: run_pre_commit
      run: pre-commit run --all-files
      shell: bash
      continue-on-error: true
    - name: Re-run pre-commit if failed
      if: steps.run_pre_commit.outcome != 'success'
      run: pre-commit run --all-files
      shell: bash
